### PR TITLE
fix: use unique keys for flow nodes

### LINKED ISSUE #78: Recovery flow: email address stays filled in the code field
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After sending the email in the recovery flow, the email stays filled in the UI, in the code field.

I think people would be quite confused about this, not realising that they need to delete the email address first and then copy-paste the code.

### Reproducing the bug

Run the next.js example, do the recovery.

### Version

master

### PR DESCRIPTION
**Pull request by zepatrik**
Closes #78 for real.

### CODE REVIEW

File: examples/nextjs-spa/src/pages/recovery.tsx [hunk 1]
```diff
@@ -84,10 +84,7 @@ const Recovery: NextPageWithLayout = () => {
         updateRecoveryFlowBody: values,
       })
       .then(({ data }) => {
-        // reset the form data completely
-        setFlow(null)
-        // Form submission was successful, show the message to the user!
-        getFlow(data.id)
```
Comment (zepatrik) [inline examples/nextjs-spa/src/pages/recovery.tsx:90]: Reverting all of these changes from https://github.com/ory/elements/commit/85cc97964328ff44488d10b35e385c070f2b2f5f because they just masked the real issue.

File: src/react-components/ory/helpers/filter-flow-nodes.tsx [hunk 2]
```diff
@@ -25,20 +25,28 @@ export const FilterFlowNodes = ({
...
+            // input node
+            "name" in node.attributes
+              ? node.attributes.name
+              : // image node
+              "src" in node.attributes
+              ? node.attributes.src
+              : // anchor, text & script node
+              "id" in node.attributes
+              ? node.attributes.id
+              : k
```
Comment (zepatrik) [inline src/react-components/ory/helpers/filter-flow-nodes.tsx:43]: This is the real fix. Previously a re-render after a flow was updated resulted in the same keys, although the input was vastly different. Because the mapping key here was the same, react did not properly re-render the input fields.
This is why index-based keys are always a bit tricky and should only be used when you are absolutely sure that the other props never change across re-renders.

Comment (Benehiko) [reply src/react-components/ory/helpers/filter-flow-nodes.tsx:43]: makes sense!

File: src/react-components/ory/helpers/filter-flow-nodes.tsx [hunk 3]
```diff
@@ -25,20 +25,28 @@ export const FilterFlowNodes = ({
...
-            node: <Node node={node} key={k} {...overrides} />,
-            hidden: true,
+    .filter((node) => includeCSRF || !(getInputName(node) === "csrf_token"))
+    .map((node, k) => ({
+      node: (
+        <Node
+          node={node}
+          key={
+            // input node
+            "name" in node.attributes
```
Comment (Benehiko) [inline src/react-components/ory/helpers/filter-flow-nodes.tsx:35]: don't we have TypeGuards for this? I believe we already use ory/integrations here, so might as well use the TypeGuards? 

https://github.com/ory/integrations/blob/main/src/ui/index.ts#L87

https://github.com/ory/integrations/blob/main/src/ui/index.ts#L54

**Review by Benehiko — CHANGES_REQUESTED** [review]

File: src/react-components/ory/helpers/filter-flow-nodes.tsx (hunk 3 above)
Comment (zepatrik) [reply src/react-components/ory/helpers/filter-flow-nodes.tsx]: Good call :+1:
