### PR TITLE
fix: totp cleared on validation error

### LINKED ISSUE #458: TOTP resets message on submit
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Ory Network Project

_No response_

### Describe the bug

https://github.com/user-attachments/assets/c331ce6a-5d0c-464a-aa9c-962ed84b0315

### Reproducing the bug

see screencase

### Relevant log output

```shell

```

### Relevant configuration

```yml

```

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aeneasr**
Closes #458

### CODE REVIEW

File: packages/elements-react/src/theme/default/components/settings/settings-totp.tsx [hunk 1]
```diff
@@ -90,17 +93,25 @@ export function DefaultSettingsTotp({
...
-                  .text,
-              }}
-            />
+            <div className="relative flex justify-stretch max-w-[488px]">
+              <input
+                disabled
+                name="totp_secret_key"
+                type="text"
+                value={
+                  (totpSecret.attributes as UiNodeTextAttributes).text.text
```
Comment (aeneasr) [inline packages/elements-react/src/theme/default/components/settings/settings-totp.tsx:102]: This input field is controlled / fixed value, <Node.Input> is a much more complex component.

**Review by jonas-jonas — APPROVED** [review]
Works well, thanks!
